// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXap8uKM7Bsy-EriAIPB50XfzQ3qOna2o',
    appId: '1:297462019909:android:a72ea65bbd2480ddad302c',
    messagingSenderId: '297462019909',
    projectId: 'ardoise-bb99a',
    storageBucket: 'ardoise-bb99a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYfhX1yEeS9UH-Y5rIC7I13qLYQPJT_Q',
    appId: '1:297462019909:ios:5d7933680d4831f2ad302c',
    messagingSenderId: '297462019909',
    projectId: 'ardoise-bb99a',
    storageBucket: 'ardoise-bb99a.appspot.com',
    iosClientId: '297462019909-ta40e79abrsi4g16394lpmcv5ae4toem.apps.googleusercontent.com',
    iosBundleId: 'com.lekitto.app',
  );
}
